### ISSUE TITLE
Mock a specific API response

### ISSUE THREAD

**Issue by SAGARSURI** [speekha/httpmocker#88]
Currently, I am looking for a way to mock a specific API request instead of the whole app?

**Comment by speekha** [comment]
How about using mixed mode? If you're in mixed mode and only provide scenarios for that specific API, it's the only one that will be mocked. Other network calls will be performed normally.

**Comment by SAGARSURI** [comment]
I will check the demo app to find the implementation for the mixed mode. Thanks for the reply.

**Comment by speekha** [comment]
The interceptor can be enabled (all calls are mocked), disabled (no call is mocked) or mixed (only available mocks are used, other calls are not mocked), or record (calls are not mocked but recorded instead). You don't need to do anything apart from setting the interceptor mode in your code to get the behavior you want.

**Comment by SAGARSURI** [comment]
Getting this error while running the demo @speekha 
```2020-03-31 19:04:44.173 23965-24149/fr.speekha.httpmocker.demo I/StaticMockProvider: Loading scenarios from repos/kotlin/ts2kt/contributors.json
2020-03-31 19:04:44.174 23965-24149/fr.speekha.httpmocker.demo E/StaticMockProvider: Scenario file could not be loaded
    java.io.FileNotFoundException: repos/kotlin/ts2kt/contributors.json
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:824)
        at android.content.res.AssetManager.open(AssetManager.java:801)
        at fr.speekha.httpmocker.demo.di.InjectionModuleKt$injectionModule$1$2$1$1.invoke(InjectionModule.kt:45)
        at fr.speekha.httpmocker.demo.di.InjectionModuleKt$injectionModule$1$2$1$1.invoke(Unknown Source:2)
        at fr.speekha.httpmocker.scenario.StaticMockProvider.loadResult(StaticMockProvider.kt:51)
        at fr.speekha.httpmocker.scenario.StaticMockProvider.loadResponse(StaticMockProvider.kt:41)
        at fr.speekha.httpmocker.io.MockResponder$mockResponseOrNull$1.invoke(MockResponder.kt:39)
        at fr.speekha.httpmocker.io.MockResponder$mockResponseOrNull$1.invoke(MockResponder.kt:25)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:129)
        at fr.speekha.httpmocker.io.MockResponder.mockResponseOrNull(MockResponder.kt:43)
        at fr.speekha.httpmocker.MockResponseInterceptor.respondToRequest(MockResponseInterceptor.kt:68)
        at fr.speekha.httpmocker.MockResponseInterceptor.intercept(MockResponseInterceptor.kt:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-03-31 19:04:44.175 23965-24149/fr.speekha.httpmocker.demo I/MockResponder: Response was found: ResponseDescriptor(delay=0, code=404, mediaType=text/plain, headers=[], body=java.io.FileNotFoundException: repos/kotlin/ts2kt/contributors.json
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:824)
        at android.content.res.AssetManager.open(AssetManager.java:801)
        at fr.speekha.httpmocker.demo.di.InjectionModuleKt$injectionModule$1$2$1$1.invoke(InjectionModule.kt:45)
        at fr.speekha.httpmocker.demo.di.InjectionModuleKt$injectionModule$1$2$1$1.invoke(Unknown Source:2)
        at fr.speekha.httpmocker.scenario.StaticMockProvider.loadResult(StaticMockProvider.kt:51)
        at fr.speekha.httpmocker.scenario.StaticMockProvider.loadResponse(StaticMockProvider.kt:41)
        at fr.speekha.httpmocker.io.MockResponder$mockResponseOrNull$1.invoke(MockResponder.kt:39)
        at fr.speekha.httpmocker.io.MockResponder$mockResponseOrNull$1.invoke(MockResponder.kt:25)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:129)
        at fr.speekha.httpmocker.io.MockResponder.mockResponseOrNull(MockResponder.kt:43)
        at fr.speekha.httpmocker.MockResponseInterceptor.respondToRequest(MockResponseInterceptor.kt:68)
        at fr.speekha.httpmocker.MockResponseInterceptor.intercept(MockResponseInterceptor.kt:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919), bodyFile=null)

**Comment by speekha** [comment]
I think that's normal. I didn't mock all the calls in the demo app so you could see how the app reacts based on the status you choose. Unless I'm mistaken, you get this error when you have set the interceptor to enabled. In this case, a missing mock is considered an error (and is translated to a 404 http error). So the list of repos is loaded, but not the corresponding contributors. If you change to mixed mode, though, the error should disappear because the proper call is going to be executed when the

**Comment by SAGARSURI** [comment]
I am getting error in both `ENABLED` and `MIXED` mode.

**Comment by speekha** [comment]
@SAGARSURI Apparently, I introduced a bug at some point: the error is thrown instead of a null. I'll look into that. Thanks for the feedback.

**Comment by SAGARSURI** [comment]
Sure. Thanks for the help and comments. 👍

**Comment by speekha** [comment]
@SAGARSURI 
Just merged a fix for the bug you found. Will publish a new version with it.

**Comment by speekha** [comment]
v1.2.0 was published last night, which includes the fix. It should work better now if you want to test again.

**Comment by SAGARSURI** [comment]
Hey @speekha now it’s working. Thanks for the quick update.
